#!/bin/bash

PARENT="blank-node-www"
ORIGIN="git@github.com:neverblued/$PARENT.git"

if [ -n "$1" ]
then
	NAME="$1"
else
	echo "# cd $PARENT"
	echo "# ./factory NAME"
	exit 1
fi

git clone $ORIGIN ../$NAME
cd ../$NAME
git remote rm origin

echo
echo "[!] $(pwd) :-->"
ls
echo
